baseURL = "https://mortal-xj.github.io/"
locale = "zh-cn"
title = "Mortal-XJ"

[taxonomies]
  tag = "tags"

[pagination]
  pagerSize = 10

[markup]
  [markup.highlight]
    style = "github"
  [markup.goldmark.renderer]
    unsafe = true

[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML"]
  page = ["HTML"]
